title: '<img src="/assets/images/logo.png" class="logo" style="height:75px; padding:10px;" /> EGRFC Playbook'

theme: just-the-docs

favicon_ico: "/assets/images/favicon.ico"

# These two lines need to change:
baseurl: ""  # Previously "/egrfc-playbook"
url: "https://egrfcplaybook.uk"  # Previously samnlindsay.github.io

# Enable relative links
relative_links:
  enabled: true

# Just the Docs navigation config (optional)
nav_sort: case_insensitive
markdown: kramdown
permalink: pretty

color_scheme: custom

nav_enabled: true
heading_anchors: true

back_to_top: false
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/samnlindsay/egrfc-playbook" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

callouts:
  attack:
    title: Attack
    color: green
  defence:
    title: Defence
    color: red
  info:
    color: blue
  example:
    color: blue
    title: Example
  note:
    title: Note
    color: red