title: "<img src='/egrfc-playbook/assets/images/logo.png' class='logo' style='height:75px; padding:10px;'/> EGRFC Playbook"
theme: just-the-docs

favicon_ico: "/assets/images/favicon.ico"

# Optional config
baseurl: "/egrfc-playbook"
url: "https://samnlindsay.github.io" # Replace with your actual GitHub Pages site

# Enable relative links
relative_links:
  enabled: true

# Just the Docs navigation config (optional)
nav_sort: case_insensitive
markdown: kramdown
permalink: pretty

color_scheme: custom

nav_enabled: true
heading_anchors: true

back_to_top: false
back_to_top_text: "Back to top"

callouts:
  attack:
    title: Attack
    color: green
  defence:
    title: Defence
    color: red
  info:
    color: blue