title: "<img src='/assets/images/logo.png' class='logo' style='height:75px; padding:10px;'/> EGRFC Playbook"
theme: just-the-docs
remote_theme: "just-the-docs/just-the-docs@v0.4.0"
plugins:
  - jekyll-seo-tag

# Optional config
url: "https://samnlindsay.github.io" # Your GitHub Pages URL
baseurl: "/egrfc-playbook" # The base URL for your project

# Enable relative links
relative_links:
  enabled: true

# Just the Docs navigation config (optional)
nav_sort: case_insensitive
markdown: kramdown
permalink: pretty

color_scheme: custom

nav_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"